---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv  # Persistent Volume 이름
spec:
  capacity:
    storage: 10Gi  # GCE Persistent Disk 크기와 동일하게 설정
  accessModes:
    - ReadWriteMany  # 여러 노드에서 동시에 읽기/쓰기 가능
  persistentVolumeReclaimPolicy: Retain  # 삭제해도 데이터를 유지하도록 설정
  storageClassName: ""
  nfs:
    server: nfs-server.default.svc.cluster.local  # NFS 서버의 내부 DNS 주소
    path: "/"  # 공유 폴더의 마운트 경로 (NFS 서버의 `/exports`)

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc  # PVC 이름 (Pod에서 참조할 PVC)
spec:
  accessModes:
    - ReadWriteMany  # 여러 노드에서 읽기/쓰기 가능
  resources:
    requests:
      storage: 10Gi  # PV의 크기와 동일해야 함
  storageClassName: ""  # PV와 동일한 StorageClass 설정
