appName: category-match
version: 231209

modelFormat: tensorflow
storageUri: pvc://nfs-pvc/model-store

resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"